
default:
  default-user-avatar: http://localhost:8080/Default_avatar/default.jpeg
  refresh-expire: 7  # 长期token时间  单位天

spring:
  web:
    resources:
      static-locations: classpath:/static/

# MyBatis配置
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-handlers-package: com.zhuxi.user.module.infrastructure.typehandler

