
bcrypt:
  strength: 10

jwt:
  admin-expire: 1800 # 单位秒
  admin-header: admin-token
  admin-secret: 0Oruxa96a/sdrtYCgkzhsZz+oUVyVKMdLu+X9aPn0Nk=
  user-secret: MkU1pCpq+8tb/XQfHGC8HpQqd6gDsGYFqRzZ5YDDojQ=
  user-expire: 1800
  user-header: user-token

cache:
  key:
    token-key: "token:user:"
    user-permission-key: "user:permission:"
    admin-permission-key: "admin:permission:"